/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wordpress_tslantz_stringendo_SoundPlayer */

#ifndef _Included_com_wordpress_tslantz_stringendo_SoundPlayer
#define _Included_com_wordpress_tslantz_stringendo_SoundPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wordpress_tslantz_stringendo_SoundPlayer
 * Method:    getMyData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wordpress_tslantz_stringendo_SoundPlayer_getMyData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
